### ISSUE TITLE
Unable to reinstall chromium

### ISSUE THREAD

**Issue by greggawatt** [nccgroup/autochrome#16]
```
ruby autochrome.rb -c
[???] Detected OS X
[---] Using locally cached Chromium version 687702
/Users/ghorton/Development/autochrome/lib/processor/macosx.rb:36:in `exist?': no implicit conversion of nil into String (TypeError)
	from /Users/ghorton/Development/autochrome/lib/processor/macosx.rb:36:in `tweak_install'
	from /Users/ghorton/Development/autochrome/lib/auto_chrome.rb:57:in `go'
	from autochrome.rb:91:in `<main>'
```

**Comment by sieunhando** [comment]
I have this error too.

**Comment by dbotamous** [comment]
This worked for me on Mac:
`ruby ./autochrome.rb -V 612451 -c`

**Comment by swarley7** [comment]
This appears to be due to the directory structure of current Chromium builds; in particular, the Chromium Framework path has changed. 

I was able to get the install to work correctly by modifying `autochrome/lib/processor/macosx.rb:9` to `FrameworkBinaryGlob = 'Contents/Frameworks/Chromium Framework.framework/Versions/Current/Chromium Framework'`.
