### ISSUE TITLE
MacOS - Unable to view "Getting Started" Page

### ISSUE THREAD

**Issue by andMYhacks** [nccgroup/autochrome#3]
When I install and run Chromium via the ruby command, I find that going to the "Getting Started" link generates the following error:

![screen shot 2017-04-28 at 2 13 52 pm](https://cloud.githubusercontent.com/assets/22803099/25541544/0f2410a8-2c1d-11e7-8458-e9dee16e71a2.png)

**Comment by RyanKoppenhaver-NCC** [comment]
Yeah, it appears that a fair amount of the profile generation functionality has stopped working with recent Chromium versions, due to changes in how preferences and extension information is stored in profiles.  (I'm guessing you didn't get colorful themes or a no-op search engine, either?)

You can see the page content [here](https://rawgit.com/nccgroup/autochrome/master/chrome_extensions/autochrome_junk_drawer/startpage/index.html) if you're curious.

**Comment by andMYhacks** [comment]
@RyanKoppenhaver-NCC You are correct on both of your guesses - no color themes, etc.

**Comment by RyanKoppenhaver-NCC** [comment]
FYI, while the getting started page and some of the other configuration is still broken, the latest dev branch should now have extensions and themes working again.

**Comment by andMYhacks** [comment]
@RyanKoppenhaver-NCC Thanks for the feedback - I'll check it out :+1:

**Comment by andMYhacks** [comment]
Accidentally closed - reopening.

**Comment by RyanKoppenhaver-NCC** [comment]
The getting started page was fixed in 62f86ca09c240717f18397b39966be296c0a5c0b (somewhat inelegantly, but that's probably going to be it for now).
