### ISSUE TITLE
Burp Extension with Custom Profiles

### ISSUE THREAD

**Issue by Loris1123** [nccgroup/autochrome#9]
I'm using Autochrome to check different user profiles. Therefore I created a seperate "person" for each profile.
However, when I'm using my own profiles, the profile is not added to the user-agent header. Hence there is no way to see the different profiles in Burp.

**Comment by RyanKoppenhaver-NCC** [comment]
AFAIK, there's no way for a chrome extension to get info about the profile.  What AutoChrome does to work around this is create a special bookmark with the profile that the extension reads.

(A UI to create/edit this field would be nice, but it's probably not going to happen unless somebody submits a patch.)

Otherwise, a workaround / manual process for you is:

1. Create the new profile.
1. Enable the integration extension for the new profile via the yellow exclamation point icon in the upper right.  (I think this is only available until you quit chromium, so you may need to recreate your profiles.)
1. Create a bookmark (cmd/ctrl-D on any page, click "more...") with the name "Autochrome Profile Name" and the URL "http://foobar", where "foobar" is the profile's name.
1. Restart Chromium.

**Comment by jabberwock** [comment]
Hi there. I do not see a yellow exclamation point icon anywhere in the browser UI. I have been unable to see any functionality from the burp extension. I followed the steps above to no avail.

**Comment by peter-h-ncc** [comment]
Closing, please re-open the issue if it is still a problem.

**Comment by michaelbehan** [comment]
It wasn't resolved so it is still a problem?
